# Enable Analog Input
CONFIG_ADC=y
# Use async mode (Optional)
# CONFIG_ADC_ASYNC=y

# Enable Analog Input Module
CONFIG_ANALOG_INPUT=y
# CONFIG_ANALOG_INPUT_LOG_LEVEL_DBG=y
# CONFIG_ANALOG_INPUT_REPORT_INTERVAL_MIN=22

# Enable logging for pre/post processed value
CONFIG_ANALOG_INPUT_LOG_DBG_RAW=y
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=y

CONFIG_ZMK_POINTING=y

# Just in case, you don't RTFM
CONFIG_INPUT=y


# 启用USB和蓝牙双模支持
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# 设置USB为默认输出（关键配置）
CONFIG_ZMK_DEFAULT_OUTPUT=USB

# 明确指定USB设备描述符
CONFIG_USB_DEVICE_VID=0x0000
CONFIG_USB_DEVICE_PID=0x0000
CONFIG_USB_DEVICE_MANUFACTURER="ZMK"
CONFIG_USB_DEVICE_PRODUCT="ZMK Keyboard"







CONFIG_I2C=n
CONFIG_ZMK_KEYBOARD_NAME="JoyStick"
